# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 12:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('creation_date', models.DateTimeField(verbose_name=datetime.datetime(2017, 6, 9, 12, 41, 4, 885853, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name=datetime.datetime(2017, 6, 9, 12, 41, 4, 886579, tzinfo=utc))),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.CUser')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name=datetime.datetime(2017, 6, 9, 12, 41, 4, 883675, tzinfo=utc))),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_of', to='exercises.CUser')),
                ('members', models.ManyToManyField(related_name='member_of', to='exercises.CUser')),
            ],
        ),
        migrations.CreateModel(
            name='Handin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handin_date', models.DateTimeField(verbose_name=datetime.datetime(2017, 6, 9, 12, 41, 4, 885045, tzinfo=utc))),
                ('text', models.TextField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Evaluation')),
                ('evaluator_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_of', to='exercises.Group')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Group')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Group'),
        ),
    ]
