# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 15:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20170609_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 6, 9, 15, 56, 58, 257793, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='handin',
            name='handin_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 6, 9, 15, 56, 58, 259014, tzinfo=utc)),
        ),
    ]
